"""
Custom Scenario Upload & Run -- lets externally-created scenario data (built
by hand, or generated by any outside tool) run through the real Stage 1-5
(+8) pipeline without an internal AI-generation step.

Two input paths:
  1. CSV, schema-matching -- validate_csv_files() checks columns and types
     against the real schema (read directly from data/raw/*.csv -- there is
     no separate "BRD Section 5" document in this repo, the schema below IS
     the ground truth, same conclusion as the "BRD Section 18" question
     earlier: verify against what actually exists, not what's assumed to).
  2. Free text -- extract_from_text() makes one real LLM call (reusing the
     exact same provider chain as Stage 8: Claude -> Gemini, no template
     fallback here, since unlike a case writeup there is no honest
     deterministic equivalent for open-ended text extraction) to turn a
     plain-language description into the same structured schema, for the
     caller to show the user before running anything.

Isolation, verified the same way as every other feature this week: never
writes to data/raw/*.csv, data/frozen_snapshot/, or data/app.db.
run_scenario() copies the real data/raw/ into a disposable tempdir
(read-only source, exactly the pattern already used by
adversarial_stress_test.py and adversarial_recommender/gap_characterizer.py),
appends the uploaded/extracted rows there, and runs the pipeline against
that copy only.

Run standalone (CSV path only -- free text needs the dashboard): none;
this module is designed to be called from frontend/app_pages/live_injection.py.
"""

import json
import shutil
import tempfile
from datetime import datetime, timedelta
from pathlib import Path

import pandas as pd
from pydantic import BaseModel

from .llm_investigate import (
    MODEL_ANTHROPIC,
    MODEL_GEMINI,
    _try_anthropic_client,
    _try_gemini_client,
    investigate_single,
)
from .pipeline.clustering import dedupe_candidates, stage2_hard_clusters, stage3_soft_clusters
from .pipeline.confounder_filter import evaluate_cluster
from .pipeline.data_io import RAW_DIR, load_data
from .pipeline.features import build_lookups, compute_features
from .pipeline.graph_build import build_graph, hard_signal_subgraph

TODAY = datetime(2026, 8, 28)

# The real schema, read from the files themselves -- required columns and a
# light type check per column. Extra columns are allowed (ignored); missing
# required columns or unparseable values are rejected with a specific error,
# never silently coerced.
SCHEMA = {
    "accounts.csv": {
        "required": ["user_id", "signup_date", "device_fingerprint_id", "ip_address_at_signup"],
        "optional": ["phone_number", "email", "referral_code_used", "referred_by_user_id",
                    "kyc_status", "home_pincode"],
        "dates": ["signup_date"],
    },
    "sessions.csv": {
        "required": ["session_id", "user_id", "device_fingerprint_id", "ip_address", "timestamp", "action_type"],
        "optional": [],
        "datetimes": ["timestamp"],
        "enum": {"action_type": {"signup", "login", "order_placed", "referral_claim"}},
    },
    "referrals.csv": {
        "required": ["referral_id", "referrer_user_id", "referred_user_id", "bonus_amount", "claim_date"],
        "optional": ["bonus_status"],
        "dates": ["claim_date"], "floats": ["bonus_amount"],
    },
    "payment_instruments.csv": {
        "required": ["user_id", "instrument_hash"],
        "optional": ["instrument_first_seen_date"],
    },
    "orders.csv": {
        "required": ["user_id", "order_id", "order_value", "order_date"],
        "optional": ["delivery_pincode"],
        "dates": ["order_date"], "floats": ["order_value"],
    },
}


def validate_csv_files(files: dict) -> tuple[bool, list[str]]:
    """files: {filename -> pandas.DataFrame}, filenames matching SCHEMA keys
    (accounts.csv is the only one that's actually required; the rest are
    optional -- a scenario can be "just accounts sharing a device" with no
    orders or referrals at all). Returns (is_valid, list of specific errors).
    Never coerces: a bad value is reported and rejected, not silently fixed."""
    errors = []
    if "accounts.csv" not in files:
        return False, ["accounts.csv is required -- at minimum, who the scenario's accounts are."]

    for name, df in files.items():
        if name not in SCHEMA:
            errors.append(f"{name}: not a recognized file (expected one of {sorted(SCHEMA.keys())}).")
            continue
        spec = SCHEMA[name]
        missing = [c for c in spec["required"] if c not in df.columns]
        if missing:
            errors.append(f"{name}: missing required column(s): {', '.join(missing)}.")
            continue  # further checks need the columns to exist

        for col in spec.get("dates", []):
            bad = _bad_rows(df, col, lambda s: pd.to_datetime(s, errors="coerce"))
            if bad:
                errors.append(f"{name}: column '{col}' has unparseable date value(s) at row(s) {bad} "
                              f"(expected YYYY-MM-DD).")
        for col in spec.get("datetimes", []):
            bad = _bad_rows(df, col, lambda s: pd.to_datetime(s, errors="coerce"))
            if bad:
                errors.append(f"{name}: column '{col}' has unparseable timestamp value(s) at row(s) {bad} "
                              f"(expected YYYY-MM-DD HH:MM:SS).")
        for col in spec.get("floats", []):
            bad = _bad_rows(df, col, lambda s: pd.to_numeric(s, errors="coerce"))
            if bad:
                errors.append(f"{name}: column '{col}' has non-numeric value(s) at row(s) {bad}.")
        for col, allowed in spec.get("enum", {}).items():
            bad_vals = set(df[col].dropna().unique()) - allowed
            if bad_vals:
                errors.append(f"{name}: column '{col}' has value(s) not in {sorted(allowed)}: {sorted(bad_vals)}.")

    if "accounts.csv" in files:
        acct_ids = set(files["accounts.csv"]["user_id"])
        for name in ("sessions.csv", "payment_instruments.csv", "orders.csv"):
            if name in files and "user_id" in files[name].columns:
                orphans = set(files[name]["user_id"]) - acct_ids
                if orphans:
                    errors.append(f"{name}: user_id value(s) not present in accounts.csv: {sorted(orphans)}.")

    return len(errors) == 0, errors


def _bad_rows(df, col, parser, limit=5):
    parsed = parser(df[col])
    bad_idx = df.index[parsed.isna() & df[col].notna()].tolist()
    return bad_idx[:limit] + (["..."] if len(bad_idx) > limit else [])


class _ExtractedAccount(BaseModel):
    user_id: str
    signup_date: str
    device_fingerprint_id: str
    ip_address_at_signup: str
    instrument_hash: str
    referred_by_user_id: str = ""
    bonus_claim_date: str = ""
    bonus_amount: float = 0.0
    order_values: list[float] = []
    order_dates: list[str] = []


class _ExtractedScenario(BaseModel):
    accounts: list[_ExtractedAccount]
    interpretation_notes: str


_EXTRACT_SYSTEM_PROMPT = """You extract structured account records from a plain-language fraud-scenario
description into a fixed schema. Every date must be YYYY-MM-DD, anchored to "today" = 2026-08-28 (e.g.
"3 days ago" -> 2026-08-25). Invent short, distinct user_id values like SCN001, SCN002. If the text says
accounts "share a device", give them the identical device_fingerprint_id string. If it says they share a
payment instrument, give them the identical instrument_hash. If timing/amounts aren't specified, pick
plausible values consistent with the rest of the description. Always fill interpretation_notes with a
plain-English restatement of exactly what you extracted, so a human can quickly confirm you read the
scenario correctly -- explicitly note anything you had to guess or invent."""


def extract_from_text(description: str, verbose: bool = True) -> dict:
    """One real LLM call (Claude -> Gemini; no template fallback -- there's no honest
    deterministic equivalent for free-text extraction). Returns the extracted structured
    scenario as a plain dict for the caller to display for confirmation before running
    anything. Raises RuntimeError if no LLM credentials are available at all."""
    anthropic_client = _try_anthropic_client(verbose)
    if anthropic_client is not None:
        try:
            response = anthropic_client.messages.parse(
                model=MODEL_ANTHROPIC, max_tokens=2048, system=_EXTRACT_SYSTEM_PROMPT,
                messages=[{"role": "user", "content": description}], output_format=_ExtractedScenario,
            )
            return {"mode": "anthropic", **response.parsed_output.model_dump()}
        except Exception as e:
            if verbose:
                print(f"Anthropic extraction failed ({type(e).__name__}: {e}); trying Gemini.")

    gemini_client = _try_gemini_client(verbose)
    if gemini_client is not None:
        try:
            from google.genai import types
            response = gemini_client.models.generate_content(
                model=MODEL_GEMINI, contents=description,
                config=types.GenerateContentConfig(
                    system_instruction=_EXTRACT_SYSTEM_PROMPT, response_mime_type="application/json",
                    response_json_schema=_ExtractedScenario.model_json_schema(),
                ),
            )
            parsed = _ExtractedScenario.model_validate_json(response.text)
            return {"mode": "gemini", **parsed.model_dump()}
        except Exception as e:
            if verbose:
                print(f"Gemini extraction failed ({type(e).__name__}: {e}).")

    raise RuntimeError(
        "Free-text extraction needs a real LLM (ANTHROPIC_API_KEY or GEMINI_API_KEY/GOOGLE_API_KEY) -- "
        "unlike Stage 8's case writeup, there's no honest deterministic fallback for open-ended text "
        "extraction. Use the CSV upload path instead, or set a credential."
    )


def extracted_to_csv_rows(extracted: dict) -> dict:
    """Expands the flat per-account extraction into the 5 real CSV shapes."""
    accounts, sessions, referrals, instruments, orders = [], [], [], [], []
    for i, a in enumerate(extracted["accounts"]):
        uid = a["user_id"]
        accounts.append({
            "user_id": uid, "signup_date": a["signup_date"], "phone_number": "", "email": "",
            "device_fingerprint_id": a["device_fingerprint_id"], "ip_address_at_signup": a["ip_address_at_signup"],
            "referral_code_used": f"REF{a['referred_by_user_id']}" if a.get("referred_by_user_id") else "",
            "referred_by_user_id": a.get("referred_by_user_id", ""), "kyc_status": "pending", "home_pincode": "",
        })
        instruments.append({"user_id": uid, "instrument_hash": a["instrument_hash"],
                            "instrument_first_seen_date": a["signup_date"]})
        sessions.append({"session_id": f"SSCN{i:04d}0", "user_id": uid,
                         "device_fingerprint_id": a["device_fingerprint_id"],
                         "ip_address": a["ip_address_at_signup"], "timestamp": a["signup_date"] + " 09:00:00",
                         "action_type": "signup"})
        if a.get("referred_by_user_id") and a.get("bonus_claim_date"):
            referrals.append({
                "referral_id": f"RSCN{i:04d}", "referrer_user_id": a["referred_by_user_id"],
                "referred_user_id": uid, "bonus_amount": a.get("bonus_amount", 0.0),
                "bonus_status": "paid", "claim_date": a["bonus_claim_date"],
            })
            sessions.append({"session_id": f"SSCN{i:04d}1", "user_id": uid,
                             "device_fingerprint_id": a["device_fingerprint_id"],
                             "ip_address": a["ip_address_at_signup"], "timestamp": a["bonus_claim_date"] + " 12:00:00",
                             "action_type": "referral_claim"})
        for j, (val, date) in enumerate(zip(a.get("order_values", []), a.get("order_dates", []))):
            orders.append({"user_id": uid, "order_id": f"OSCN{i:04d}{j}", "order_value": val,
                           "order_date": date, "delivery_pincode": ""})
            sessions.append({"session_id": f"SSCN{i:04d}{2+j}", "user_id": uid,
                             "device_fingerprint_id": a["device_fingerprint_id"],
                             "ip_address": a["ip_address_at_signup"], "timestamp": date + " 15:00:00",
                             "action_type": "order_placed"})
    all_files = {"accounts.csv": pd.DataFrame(accounts), "sessions.csv": pd.DataFrame(sessions),
                "referrals.csv": pd.DataFrame(referrals), "payment_instruments.csv": pd.DataFrame(instruments),
                "orders.csv": pd.DataFrame(orders)}
    # An empty extraction (e.g. no referral chain described in the text) produces a
    # DataFrame with zero rows and, critically, zero inferred columns -- passing that
    # through to validate_csv_files() would report every required column as "missing"
    # for a file that was never meant to exist in the first place. Drop it instead;
    # accounts.csv is never empty by construction (there's nothing to run otherwise).
    return {name: df for name, df in all_files.items() if len(df) > 0}


def run_scenario(files: dict, run_llm: bool = True, verbose: bool = True) -> dict:
    """files: {filename -> DataFrame}, already validated. Copies the real data/raw/ into a
    disposable tempdir, appends the uploaded rows, runs Stages 1-5 (and Stage 8 if run_llm)
    against that copy only -- data/raw/, data/frozen_snapshot/, and data/app.db are never
    opened for writing anywhere in this function. Returns the same outcome shape as
    backend/live_injection.py's inject_and_detect(), so the dashboard reuses its rendering."""
    tmp = Path(tempfile.mkdtemp(prefix="sentinel_custom_scenario_"))
    try:
        member_set = set(files["accounts.csv"]["user_id"])
        for name in SCHEMA:
            existing = pd.read_csv(RAW_DIR / name, dtype=str)
            new_rows = files.get(name)
            if new_rows is not None and len(new_rows):
                combined = pd.concat([existing, new_rows.astype(str)], ignore_index=True)
            else:
                combined = existing
            combined.to_csv(tmp / name, index=False)

        data = load_data(raw_dir=tmp)
        G = build_graph(data)
        H = hard_signal_subgraph(G)
        hard_clusters = stage2_hard_clusters(H)
        soft_clusters = stage3_soft_clusters(G)
        candidates = dedupe_candidates(hard_clusters, soft_clusters)
        device_by_user, instrument_by_user = build_lookups(data)

        matched = None
        for i, (members, stage) in enumerate(candidates):
            overlap = member_set & members
            if len(overlap) >= max(2, len(member_set) // 2):
                feats = compute_features(G, members, data, device_by_user, instrument_by_user)
                verdict = evaluate_cluster(feats)
                matched = {"cluster_id": f"SCN{i:04d}", "detection_stage": stage, "members": sorted(members),
                          "features": feats, "flagged": verdict["flagged"], "filter_reason": verdict["reason"],
                          "organic_score": verdict["organic_score"], "suspicion_score": verdict["suspicion_score"]}
                break

        # G is kept in the returned outcome -- the real dashboard graph (shared.get_graph())
        # never contains these accounts, by design (isolation), so the caller must render
        # from this scratch-built graph instead. Safe to keep after cleanup: G was already
        # built from data already loaded into memory, not read lazily from tmp.
        outcome = {"members": sorted(member_set), "size": len(member_set), "matched_cluster": matched,
                  "kind": matched["detection_stage"] if matched else "custom", "graph": G}
        if matched is None:
            outcome["status"] = "not_clustered"
            if verbose:
                print("The uploaded scenario did not form a candidate cluster at all.")
            return outcome

        if not matched["flagged"]:
            outcome["status"] = "clustered_not_flagged"
            outcome["filter_reason"] = matched["filter_reason"]
            if verbose:
                print(f"Clustered as {matched['cluster_id']} but NOT flagged: {matched['filter_reason']}")
            return outcome

        outcome["status"] = "flagged"
        if run_llm:
            outcome["case"] = investigate_single(matched, verbose=verbose, persist=False)
        if verbose:
            print(f"Flagged as {matched['cluster_id']}"
                  + (f" -> {outcome['case']['recommended_action']}" if run_llm else ""))
        return outcome
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
